### ISSUE TITLE
[Bug] interface conversion: interface {} is nil, not string

### ISSUE THREAD

**Issue by jkoking** [Vanilla-OS/Albius#28]
![Screenshot_20231015_214321](https://github.com/Vanilla-OS/vanilla-installer/assets/72178490/e73bdda5-59ab-426e-88e5-a0cf1248ea9f)

**Comment by matbme** [comment]
Does this issue still happen on the latest ISO?

**Comment by jkoking** [comment]
No, the  latest ISO work's.
