### ISSUE TITLE
Albius can't delete LVM partitions, me either

### ISSUE THREAD

**Issue by iWisp360** [Vanilla-OS/Albius#38]
When i was testing vanilla in vm, albius made 2 lvm partitions, but after the installation failed(the bootloader didn't install properly) albius couldn't delete the partitions after selecting the previously used virtual disk, so the installer failed, i tried to delete the lvm partitions in gparted and i needed to use a nixos disk to delete them because the volumes were active.

**Comment by taukakao** [comment]
Yup, you can't currently reinstall Vanilla over an existing vanilla install. 
I forgot to write that issue, so thanks for doing that. ^^

But you can actually delete them manually, you just have to deactivate the volume group with vgchange if I remember correctly.

**Comment by iWisp360** [comment]
I did something like that with gparted to reinstall vanilla, but the volumes didn't deactivate

**Comment by axtloss** [comment]
You can remove the lvm volumes using `sudo lvremove /dev/mapper/vos*`, this will delete any vanilla os lvm volumes and allows repartitioning again.
